### PR TITLE
Update decorator pattern sample

### PR DESCRIPTION
**Pull request by clarity-team**

### CODE REVIEW

**Comment by clarity-team** [comment]
@clarity-bot diff

**Comment by clarity-team** [comment]
@clarity-bot diff

**Comment by clarity-team** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Comment by Zir0-93** [comment]
@clarity-bot diff

**Pull request merged**
